version: 2

sources:
  - name: northwind
    description: Data from northwind ERP
    database: curso-etl-101  
    schema: erp_northwind  
    tables:
      - name: orders
        description: '{{ doc("orders_docs") }}'
        columns:
          - name: order_id
            description: Unique ID for this table
      - name: customers
        columns:
          - name: customer_id
            description: Unique ID for this table
      - name: orders_details

 